---
kvm:
  children:
    kvm_controller:
      hosts:
        kvm_controller_1:
          ansible_host: 192.168.1.100
    kvm_worker:
      hosts:
        kvm_1:
          ansible_host: 192.168.1.100
        kvm_2:
          ansible_host: 192.168.1.101

ovn:
  children:
    ovn_controller:
      hosts:
        ovn_controller_1:
          ansible_host: 192.168.1.110
    ovn_host:
      hosts:
        ovn_1:
          ansible_host: 192.168.1.111
        ovn_2:
          ansible_host: 192.168.1.112
