---
dhcp:
  hosts:
    dhcp_1:
      ansible_host: 192.168.1.100

dns:
  hosts:
    dns_1:
      ansible_host: 192.168.1.100

kvm:
  hosts:
    kvm_1:
      ansible_host: 192.168.1.101

ovn_central:
  hosts:
    ovn_central_1:
      ansible_host: 192.168.1.110

ovn_host:
  hosts:
    ovn_host_1:
      ansible_host: 192.168.1.111
    ovn_host_2:
      ansible_host: 192.168.1.112
