---
# build
ovs_repo: https://github.com/openvswitch/ovs.git
ovs_version: v3.0.0
ovs_repo_dir: /opt/ovs

ovn_repo: https://github.com/ovn-org/ovn.git
ovn_version: v22.06.0
ovn_repo_dir: /opt/ovn

ovn_requirements_packages_dnf:
  - name: git
    state: latest
  - name: make
    state: latest
  - name: gcc
    state: latest
  - name: autoconf
    state: latest
  - name: automake
    state: latest
  - name: libtool
    state: latest
  - name: systemd
    state: latest
  - name: openssl
    state: latest
  - name: openssl-devel
    state: latest
  - name: python3
    state: latest
  - name: python3-devel
    state: latest
  - name: python3-six
    state: latest
  - name: python3-setuptools
    state: latest
  - name: python3-pip
    state: latest
  - name: desktop-file-utils
    state: latest
  - name: groff-base
    state: latest
  - name: groff
    state: latest
  - name: graphviz
    state: latest
  - name: procps-ng
    state: latest
  - name: libcap-ng
    state: latest
  - name: libcap-ng-devel
    state: latest
  - name: openssl
    state: latest
  - name: hostname
    state: latest
  - name: iproute
    state: latest
  - name: libibverbs
    state: latest

ovn_requirements_packages_pip:
  - sphinx==5.3.0
  - pyOpenSSL==22.1.0

# start
ovs_etc_dir: /etc/openvswitch
ovs_log_dir: /var/log/openvswitch
ovs_run_dir: /var/run/openvswitch
ovn_etc_dir: /etc/ovn
ovn_log_dir: /var/log/ovn
ovn_run_dir: /var/run/ovn

ovn_nb_db_name: ovnnb_db
ovn_sb_db_name: ovnsb_db

ovn_nb_db_schema_file_path: "{{ ovn_repo_dir }}/ovn-nb.ovsschema"
ovn_sb_db_schema_file_path: "{{ ovn_repo_dir }}/ovn-sb.ovsschema"

ovn_nb_port: 6641
ovn_sb_port: 6642

# setting
ovn_nb_db_socket: unix:{{ ovn_run_dir }}/{{ ovn_nb_db_name }}.sock

ovn_overlay_switch: sw
ovn_overlay_switch_port:
  router:
    name: sw-rt

ovn_public_switch: public
ovn_public_switch_port:
  router:
    name: public-rt
  local:
    name: public-local

ovn_physical_network_name: phynet

ovn_router: rt
ovn_default_route: 192.168.1.254
ovn_snat_src: 10.0.0.0/8

ovn_router_port:
  overlay:
    name: rt-sw
    mac: 96:2a:9f:22:92:90
    ip: 10.255.255.254
    subnet_length: 8
  public:
    name: rt-public
    mac: 6a:10:b5:75:18:3e
    ip: 192.168.1.253
    subnet_length: 24
