---

ovn_remote_ip: 192.168.1.100
ovn_nb_port: 6641
ovn_nb_db: "tcp:{{ ovn_remote_ip }}:{{ ovn_nb_port }}"

vm_list:
  # infra: 10.0.0.0/24
  - name: dhcp
    iface_list:
      - ip: 10.0.0.1
        mac: 4a:ed:0a:98:f7:a8
        ovs_id: dd070f3e-318d-73d3-baa7-fd9c72947f6c
        ovn_switch: sw
        ovn_router: rt
    uuid: db1a0b4a-80ab-8d19-ba45-41614e5e2389
    vcpu: 1
    memory_KiB: "{{ 2 * 1024 * 1024 }}"
    base_os: rocky9.0
    meta:
      state: none
      host: kvm_1
  - name: dns
    iface_list:
      - ip: 10.0.0.2
        mac: 4a:a5:72:29:f8:eb
        ovs_id: 4e513660-3e09-4ae7-5329-26ac2d726b03
        ovn_switch: sw
        ovn_router: rt
    uuid: 8b962cf9-0f77-362a-fe6a-a46b241bffaf
    vcpu: 1
    memory_KiB: "{{ 2 * 1024 * 1024 }}"
    base_os: rocky9.0
    meta:
      state: none
      host: kvm_1
  - name: ansible
    iface_list:
      - ip: 10.0.0.3
        mac: 86:97:14:21:02:c6
        ovs_id: fc40a8fa-9519-e427-02be-92c9787da5e4
        ovn_switch: sw
        ovn_router: rt
    uuid: cad53202-cff2-0fcf-64d9-f6aec69fb903
    vcpu: 2
    memory_KiB: "{{ 4 * 1024 * 1024 }}"
    base_os: rocky9.0
    meta:
      state: none
      host: kvm_2
  - name: ca
    iface_list:
      - ip: 10.0.0.4
        mac: 0e:79:13:4d:b5:0f
        ovs_id: eb4ab218-d1c5-b11e-62a0-9cfa921bd926
        ovn_switch: sw
        ovn_router: rt
    uuid: 4d39a5c6-c1ca-9e60-0431-b789db87f351
    vcpu: 1
    memory_KiB: "{{ 2 * 1024 * 1024 }}"
    base_os: rocky9.0
    meta:
      state: none
      host: kvm_1

  # service: 10.0.10.0/24
  - name: front_ca
    iface_list:
      - ip: 10.0.10.1
        mac: e2:8e:eb:ff:41:86
        ovs_id: d9939b6f-d1cf-8a25-2c39-cf0c94ab809a
        ovn_switch: sw
        ovn_router: rt
    uuid: d123f093-77aa-9e2b-0e8c-e5fa54037a3b
    vcpu: 2
    memory_KiB: "{{ 4 * 1024 * 1024 }}"
    base_os: rocky9.0
    meta:
      state: none
      host: kvm_1
  - name: front_minio_web
    iface_list:
      - ip: 10.0.10.10
        mac: 62:9b:cf:69:30:b3
        ovs_id: 45010ea9-640e-be92-a244-324a5b6a7e27
        ovn_switch: sw
        ovn_router: rt
    uuid: c2194830-f8a7-a3f7-2347-3b37ed84df69
    vcpu: 2
    memory_KiB: "{{ 4 * 1024 * 1024 }}"
    base_os: rocky9.0
    meta:
      state: none
      host: kvm_1
  - name: front_minio_api
    iface_list:
      - ip: 10.0.10.11
        mac: 0a:b5:eb:23:57:3f
        ovs_id: 30f1aa5b-744c-b69b-3256-81d901a4d951
        ovn_switch: sw
        ovn_router: rt
    uuid: faae9b3c-ad4e-acc3-2aef-8dcaaaece71f
    vcpu: 2
    memory_KiB: "{{ 4 * 1024 * 1024 }}"
    base_os: rocky9.0
    meta:
      state: none
      host: kvm_2

  # backend: 10.0.20.0/24
  - name: aia_1
    iface_list:
      - ip: 10.0.20.1
        mac: b6:5b:43:82:b2:6b
        ovs_id: cde7523d-929a-46df-acff-ca23f77fb60c
        ovn_switch: sw
        ovn_router: rt
    uuid: 0f6da437-d6e7-ef2e-016a-5f4ec1f89026
    vcpu: 1
    memory_KiB: "{{ 2 * 1024 * 1024 }}"
    base_os: rocky9.0
    meta:
      state: none
      host: kvm_1
  - name: minio_1
    iface_list:
      - ip: 10.0.20.10
        mac: be:24:71:28:18:f7
        ovs_id: 7c2d3043-8697-b22b-21d2-64ad752cde5c
        ovn_switch: sw
        ovn_router: rt
    uuid: 1e74b6f5-0a99-1de2-cda6-e0fbae0510ea
    vcpu: 2
    memory_KiB: "{{ 4 * 1024 * 1024 }}"
    base_os: rocky9.0
    meta:
      state: none
      host: kvm_2

  # rocky: 10.10.0.0/24
  - name: rocky_1
    iface_list:
      - ip: 10.10.0.1
        mac: 46:38:51:8e:0e:bb
        ovs_id: 5f58cdf5-b3d6-c6e6-62f8-80a292d05bb4
        ovn_switch: sw
        ovn_router: rt
    uuid: 3b6346a3-99fe-4aea-62e1-b75d4a85df57
    vcpu: 8
    memory_KiB: "{{ 32 * 1024 * 1024 }}"
    base_os: rocky9.0
    meta:
      state: none
      host: kvm_1
  - name: rocky_2
    iface_list:
      - ip: 10.10.0.2
        mac: 5a:73:02:a8:f5:ff
        ovs_id: c7fc93bf-1381-1203-7621-b15ec79ff6e3
        ovn_switch: sw
        ovn_router: rt
    uuid: 17ba4b69-0dcc-0ef1-7549-3885abe5b01c
    vcpu: 8
    memory_KiB: "{{ 32 * 1024 * 1024 }}"
    base_os: rocky9.0
    resized_volume:
      disk_size: 200G
      expand_partition: /dev/sda2
      expand_lv: /dev/rl/root
    meta:
      state: none
      host: kvm_2

  # ubuntu: 10.20.0.0/24
  - name: ubuntu_1
    iface_list:
      - ip: 10.20.0.1
        mac: 2a:7a:b8:15:7c:6a
        ovs_id: 0c40f183-90af-e82b-7cd1-2c485e69c11c
        ovn_switch: sw
        ovn_router: rt
    uuid: 912a696b-6a31-3caa-f445-fc30321e7a35
    vcpu: 8
    memory_KiB: "{{ 32 * 1024 * 1024 }}"
    base_os: ubuntu22.04
    meta:
      state: none
      host: kvm_1
  - name: ubuntu_2
    iface_list:
      - ip: 10.20.0.2
        mac: 6a:11:26:40:0b:d4
        ovs_id: b5f5168e-30cc-8c9b-0aab-8163404980e0
        ovn_switch: sw
        ovn_router: rt
    uuid: 5e966a7d-ad15-431a-3125-ab8ce8619bda
    vcpu: 8
    memory_KiB: "{{ 32 * 1024 * 1024 }}"
    base_os: ubuntu22.04
    meta:
      state: none
      host: kvm_2
