---

subnet: 10.0.0.0
netmask: 255.0.0.0

broadcast_address: 10.255.255.255
routers: 10.255.255.254
domain_name_servers: 10.0.0.2
interface_mtu: 1400
range: 10.0.0.200 10.0.0.254

host_list:
  # infra
  - name: dhcp
    iface_list:
      - ip: 10.0.0.1
        mac: 4a:ed:0a:98:f7:a8
  - name: dns
    iface_list:
      - ip: 10.0.0.2
        mac: 4a:a5:72:29:f8:eb
  - name: ansible
    iface_list:
      - ip: 10.0.0.3
        mac: 86:97:14:21:02:c6
  - name: ca
    iface_list:
      - ip: 10.0.0.4
        mac: 0e:79:13:4d:b5:0f

  # front
  - name: front_ca
    iface_list:
      - ip: 10.0.10.1
        mac: e2:8e:eb:ff:41:86
  - name: front_minio_web
    iface_list:
      - ip: 10.0.10.10
        mac: 62:9b:cf:69:30:b3
  - name: front_minio_api
    iface_list:
      - ip: 10.0.10.11
        mac: 0a:b5:eb:23:57:3f
  - name: front_k8s
    iface_list:
      - ip: 10.0.10.20
        mac: ea:2d:bd:59:f2:f4

  # back
  - name: ca_1
    iface_list:
      - ip: 10.0.20.1
        mac: b6:5b:43:82:b2:6b
  - name: k8s_controller_1
    iface_list:
      - ip: 10.0.20.20
        mac: 42:fb:e9:1f:be:78
  - name: k8s_worker_1
    iface_list:
      - ip: 10.0.20.30
        mac: de:d7:e2:00:f2:19
  - name: k8s_worker_2
    iface_list:
      - ip: 10.0.20.31
        mac: aa:d1:03:f1:6e:a8

  # test vm
  - name: r1
    iface_list:
      - ip: 10.10.0.1
        mac: 46:38:51:8e:0e:bb
  - name: r2
    iface_list:
      - ip: 10.10.0.2
        mac: 5a:73:02:a8:f5:ff
  - name: rocky_small_1
    iface_list:
      - ip: 10.10.0.20
        mac: aa:02:ee:d4:0f:4a
  - name: u1
    iface_list:
      - ip: 10.20.0.1
        mac: 2a:7a:b8:15:7c:6a
  - name: u2
    iface_list:
      - ip: 10.20.0.2
        mac: 6a:11:26:40:0b:d4
