---
local_address: "10.0.0.2"

record_list:
  - host: dhcp
    ip: 10.0.0.1
  - host: dns
    ip: 10.0.0.2

  # front
  - host: ca.cloud
    ip: 10.0.10.1
  - host: www.minio.cloud
    ip: 10.0.10.10
  - host: api.minio.cloud
    ip: 10.0.10.11

  # back
  - host: aia-1
    ip: 10.0.20.1

  # test
  - host: minio-1
    ip: 10.10.0.1
