---
local_address: "10.0.0.2"

record_list:
  - host: dhcp
    ip: 10.0.0.1
  - host: dns
    ip: 10.0.0.2

  - host: minio-1
    ip: 10.10.0.1

  - host: www.minio.cloud
    ip: 10.0.10.10
  - host: api.minio.cloud
    ip: 10.0.10.11
