---
haproxy_cert_dir: /opt/cert

haproxy_list:
  - hostname: ca_web
    fqdn: ca.cloud.localdomain
    ssl: false
    backend_servers:
      - hostname: aia-1
        ip: 10.0.20.1
        port: 80
        ssl: false
  - hostname: minio_web
    fqdn: www.minio.cloud.localdomain
    ssl: true
    backend_servers:
      - hostname: minio-1
        ip: 10.10.0.20
        port: 9090
        ssl: true
  - hostname: minio_api
    fqdn: api.minio.cloud.localdomain
    ssl: true
    backend_servers:
      - hostname: minio-1
        ip: 10.10.0.20
        port: 9000
        ssl: true
  - hostname: k8s_controller
    fqdn: api.k8s.cloud.localdomain
    ssl: true
    backend_servers:
      - hostname: k8s_controller_1
        ip: 10.0.0.20
        port: 6443
        ssl: false
