---
haproxy_cert_dir: /opt/cert

haproxy_list:
  - hostname: minio_web
    fqdn: www.minio.cloud.localdomain
    backend_servers:
      - hostname: minio-1
        ip: 10.10.0.1
        port: 9090
        ssl: true
  - hostname: minio_api
    fqdn: api.minio.cloud.localdomain
    backend_servers:
      - hostname: minio-1
        ip: 10.10.0.1
        port: 9000
        ssl: true
